### PR TITLE
fix obvious eclipse warnings

### PR DESCRIPTION
**Pull request by vasvir**

### CODE REVIEW

**Comment by eemi2010** [comment]
Thx. But gwt-tour is not maintained anymore. I moved this lib to the ahome namespace and combined it with IntroJS

**Comment by vasvir** [comment]
Hi,

Sorry to hear that. Is this the correct (maintained) gwt-tour
https://github.com/ahome-it/gwt-tour ?

If yes I can create pull requests against that if don't have any
objections...

```
Vassilis
```

On Fri, Jun 5, 2015 at 11:51 PM, Ekambos notifications@github.com wrote:

> Thx. But gwt-tour is not maintained anymore. I moved this lib to the ahome
> namespace and combined it with IntroJS
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eemi2010/gwt-tour/pull/20#issuecomment-109435370.

## 

Vassilis Virvilis

**Comment by eemi2010** [comment]
Yes That s the new project.
Sure. Pull Request are always welcome :)

**Comment by vasvir** [comment]
Ehm...

Looks like it depends on ahome-core. I am not sure I want to depend on that
library - looks biggish

May I ask what's the point of having two hopscotch wrappers? If you really
want to deprecate the
eemi2010/gwt-tour I think you should put a redirect message on the README.md

   Vassilis

On Sat, Jun 6, 2015 at 1:29 AM, Ekambos notifications@github.com wrote:

> Yes That s the new project.
> Sure. Pull Request are always welcome :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eemi2010/gwt-tour/pull/20#issuecomment-109464496.

## 

Vassilis Virvilis

**Comment by vasvir** [comment]
Ok I imported also ahome-core. I am getting out a bit off topic here so I
am open to suggestions on if we should and where we should continue the
discussion.

Issues:

1) ahome-gwt-tour cannot find resources js/css and later on png. I have
noticed that there is a sibling (to src/) resources directory but it is not
beeing picked up. I have downloaded latest hopscotch files in the
src/././resources directory for proper inclusion. Furthermore with a nifty
hack I was able to load the hopscotch sprite in a url free way without
bothering the main application with hopscotch resources.

2) ahome-core gives me 22 warnings. The biggest categories are:
    a) missing @override: obvious
    b) unnecessary casts (Oject): obvious everything is an object in java
    c) unnecessary else statements: This is not obvious as it is largely a
personal or company coding style. In my settings it is a warning the
following pattern

if (condition) {
return a;
} else {
return b;
}

but other people / companies may not like the

if (condition) {
return a;
}
return b;

So the questions are: What is the preferred way to add resources to 1) and
if you want to send pull requests for 2) and for which subclasses of
warnings?

Thanks for the had work

   Vassilis

**Comment by eemi2010** [comment]
1 ) Yes. there is a bug about loading Hopscoth resources. Will try to fix that asap. Just been busy with other stuff. If you beat me to it I 
2 )  Pull request are always welcome. If you see need to fix something go ahead :)

**Comment by vasvir** [comment]
Created pull requests
1. https://github.com/ahome-it/gwt-tour/pull/2
2. https://github.com/ahome-it/ahome-core/pull/5
   
   Vassilis

On Tue, Jun 9, 2015 at 10:21 AM, Ekambos notifications@github.com wrote:

> 1 ) Yes. there is a bug about loading Hopscoth resources. Will try to fix
> that asap. Just been busy with other stuff. If you beat me to it I
> 2 ) Pull request are always welcome. If you see need to fix something go
> ahead :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eemi2010/gwt-tour/pull/20#issuecomment-110257149.

## 

Vassilis Virvilis

**Pull request merged**
